### ISSUE TITLE
each criteria should link to its acceptance-discussion thread

### ISSUE THREAD

**Issue by rxgrant** [w3c/did-rubric#64]
All rubric criteria should have public discussion threads available as a historical record, where subject matter experts can offer the best references to support the best arguments.

These issues are expected to be active discussions while the criteria is new, and closed when the criteria's pull request is approved.

This issue will be complete when:
* the WG has actually accepted this idea;
* instructions to criteria authors are clear;
* a template for linking to the issues is available; and
* all existing critera have such links, even if the issues are closed (but probably leave them open until the Rubric reaches 1.0).

**Comment by jandrieu** [comment]
At this point even your co-editor doesn't feel the W3C is the place to facilitate and archive broad discussion about criteria.

I say this because that such discussion will be ongoing, over time, with people who aren't part of the W3C community. It needs a discursive mechanism that the W3C doesn't have and probably doesn't have the institutional constitution to manage. In contrast to the publish & persist model of Recommendations and Notes, a proper record of ongoing discussion is a many headed hydra that, IMO, needs more than can be supported through Github issues.

**Comment by rxgrant** [comment]
After discussion, this would not be a scalable way to proceed.  

However, critera may end up with external links detailing discussion, based on the editors' judgement about whether the link is to an appropriate forum for the debate.
